baseURL = 'https://david206.github.io/'
locale = 'en-us'
title = 'Blog by David Shimon'
theme = 'nostyleplease'

defaultContentLanguage = 'he'
defaultContentLanguageInSubdir = true
[languages]
  [languages.he]
    contentDir = 'content/he'
    disabled = false
    locale = 'he-IL'
    direction = 'rtl'
    label = 'Hebrew'
    title = 'הבלוג של דוד'
    weight = 1
    [languages.he.params]
      subtitle = 'TBD'
  [languages.en]
    contentDir = 'content/en'
    disabled = false
    locale = 'en-US'
    direction = 'ltr'
    label = 'English'
    title = 'Blog by David Shimon'
    weight = 2
    [languages.en.params]
      subtitle = 'TBD'

[caches]
  [caches.images]
    dir = ':cacheDir/images'
